### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Joby-Tech** [BitcoinGold-mining/z-nomp-bitcoin-gold#1]
Dear All, when i try mining receive error:

Example:

Share processor Redis execution time: 3 Executed operations: 6
Invalid solution: invalid collision length between StepRows
X[i]   = df7c33523f944e07cd1f25040b694955947b
X[i+1] = a845437075dac73bc1c1d1706da700292c48
2020-04-07 22:07:19 [Pool]      [bitcoin gold] (Thread 1) Share rejected: {"job":"cccd","ip":"::ffff:X.X.X.X","worker":"XXXXX.worker","difficulty":0.125,"error":"invalid solution"}

**Comment by h4x3rotab** [comment]
Does it occur all the time? If so, you may need to check your miner config.
Otherwise it may just be some occasional bad solutions produced by a trade
off mining strategy. It normal.

**Comment by Joby-Tech** [comment]
Yes, its always.. All solutions... From miner side: Found share.. Side pool:  Share processor Redis execution time: 3 Executed operations: 6
 Invalid solution: invalid collision length between StepRows

But miner is OK.. Testing on differents pools...

**Comment by Joby-Tech** [comment]
May be same problem with redis or equihashverify?

**Comment by h4x3rotab** [comment]
Are you using the master branch?

**Comment by Joby-Tech** [comment]
Yes, build from clone: https://github.com/poolgold/z-nomp-bitcoin-gold.git

**Comment by h4x3rotab** [comment]
Then it's the problem. Please build from
"BitcoinGold-mining/z-nomp-bitcoin-gold"

Joby-Tech <notifications@github.com> 于2020年4月11日周六 下午10:16写道：

**Comment by Joby-Tech** [comment]
h4x3rotab,

Yes, thank you! now is ok...
and to remove error "address verification" at startup pool need change in paymentProcessor.js: getaddressinfo to validateaddress (99 and 116 strings)
